# Generated by Django 5.0.3 on 2024-04-09 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecommendation', '0002_payment_userbook_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1976.430000000000063664629124104976654052734375'), max_digits=6),
        ),
    ]
